### PR TITLE
Update RxAndroid/RxJava to latest

### PR DESCRIPTION
**Pull request by bidluo**
As per issue #24. Works fine locally, though since we don't have any tests yet it's hard to tell if I broke anything.

### CODE REVIEW

**Comment by mhdatie** [comment]
When trying to make modules app it throws a missing Android Manifest error 

Error:Android Source Generator: [Redgram] AndroidManifest.xml file not found

**Comment by bidluo** [comment]
Not sure what would cause that as the manifest is clearly there and making the `app` module works fine on my end. Perhaps try rebuild/clean? Chances are, it's because of the gradle update

**Comment by mhdatie** [comment]
Cleaning the project didn't work. I can switch between master and dev-settings with no problems but not to dev. For now I am reverting to HEAD -1 :
1. git fetch origin dev
2. git pull
3. git reset --hard 096e2a7ce52c2539eddd541a9a1a696436bcc9e0

We need someone else to update their repository and confirm nothing went wrong with them

**Comment by fbis251** [comment]
This pull request worked fine for me, I just built and installed the APK using commit 03025c2f05489afe04f14e9d9326d854bf231e69

**Comment by mhdatie** [comment]
Weird, I will spend more time on it then

**Comment by ericfabreu** [comment]
The app is building here too

**Comment by mhdatie** [comment]
I got it to work too. Thanks to @bidlou 's tip, I had to delete the idea folder and reopen the project.

**Pull request merged**
