### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Patyfatycake**
Some lint cleanup

### CODE REVIEW

**Comment by mhdatie** [comment]
Did you build and run the project before your changes? I'm busy trying to make this project more collaborative so I might not find time to test this.

**Comment by Patyfatycake** [comment]
Il try again when I get home again.... Ci worked and there are no large refactors.

**Comment by Patyfatycake** [comment]
Yep works fine like last night. Don't know what issues you might have seen, probably should add some unit tests to the project.

**Comment by Patyfatycake** [comment]
Sooo?

**Comment by mhdatie** [comment]
Hey @Patyfatycake sorry couldn't get back to you...I was not saying there was a problem, it's just that any commit has to be tested to make sure it doesn't break anything and since this was a huge cleanup there could be run time errors somewhere. @ninadmg merged your commit so it should be good.

**Pull request merged**
